#pragma warning disable RS1035

using System;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sourcy;

public abstract class BaseSourcyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rootDirectoryValuesProvider = context.CompilationProvider
            .Select((compilation, _) => GetRoot(compilation));

        context.RegisterSourceOutput(rootDirectoryValuesProvider, Initialize);
    }

    protected abstract void Initialize(SourceProductionContext context, Root root);

    protected static Root? GetRootDirectory(string? path)
    {
        if (path is null)
        {
            return null;
        }
        
        var location = GetLocation(path);

        // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
        while (location is not null)
        {
            if (Directory.Exists(Path.Combine(location.FullName, ".git")))
            {
                break;
            }

            if (File.Exists(Path.Combine(location.FullName, ".sourcyroot")))
            {
                break;
            }

            location = location.Parent;
        }

        if (location is null)
        {
            return null;
        }

        return new Root(location);
    }

    protected static DirectoryInfo GetLocation(string path)
    {
        return new FileInfo(path).Directory!;
    }

    protected static Root GetRoot(Compilation compilation)
    {
        var assemblyLocations = compilation.Assembly.Locations;

        return assemblyLocations
                   .Where(x => x.Kind == LocationKind.MetadataFile)
                   .Select(x => GetRootDirectory(Directory.GetParent(x.GetLineSpan().Path)!.FullName))
                   .OfType<Root>()
                   .FirstOrDefault()
               ?? assemblyLocations
                   .Select(x => GetRootDirectory(Directory.GetParent(x.GetLineSpan().Path)!.FullName))
                   .OfType<Root>()
                   .First();
    }

    private static Location GetFileLocation(ImmutableArray<Location> assemblyLocations)
    {
        return assemblyLocations
                                 .FirstOrDefault(x => x.Kind is LocationKind.MetadataFile && !x.SourceSpan.ToString().Contains("<auto-generated"))
                             ?? assemblyLocations.First(x => !x.SourceSpan.ToString().Contains("<auto-generated"));
    }

    protected static SourceText GetSourceText([StringSyntax("c#")] string code)
    {
        return SourceText.From(code, Encoding.UTF8);
    }
}