#pragma warning disable RS1035

using System;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sourcy;

public abstract class BaseSourcyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rootDirectoryValuesProvider = context.CompilationProvider
            .Select((compilation, _) => GetLocation(compilation))
            .Select((directory, _) => GetRootDirectory(directory));

        context.RegisterSourceOutput(rootDirectoryValuesProvider, Initialize);
    }

    protected abstract void Initialize(SourceProductionContext context, Root root);

    protected static Root GetRootDirectory(string path)
    {
        DirectoryInfo? location = GetLocation(path);

        // ReSharper disable once ConditionIsAlwaysTrueOrFalseAccordingToNullableAPIContract
        while (location is not null)
        {
            if (Directory.Exists(Path.Combine(location.FullName, ".git")))
            {
                break;
            }

            if (File.Exists(Path.Combine(location.FullName, ".sourcyroot")))
            {
                break;
            }

            location = location.Parent;
        }

        if (location is null)
        {
            throw new ArgumentNullException(nameof(location));
        }

        return new Root(location);
    }

    protected static DirectoryInfo GetLocation(string path)
    {
        return new FileInfo(path).Directory!;
    }

    protected static string GetLocation(Compilation compilation)
    {
        var assemblyLocations = compilation.Assembly.Locations;

        var fileLocation = GetFileLocation(assemblyLocations);

        return Directory.GetParent(fileLocation.GetLineSpan().Path)!.FullName!;
    }

    private static Location GetFileLocation(ImmutableArray<Location> assemblyLocations)
    {
        return assemblyLocations
                                 .FirstOrDefault(x => x.Kind is LocationKind.MetadataFile && !x.SourceSpan.ToString().Contains("<auto-generated"))
                             ?? assemblyLocations.First(x => !x.SourceSpan.ToString().Contains("<auto-generated"));
    }

    protected static SourceText GetSourceText([StringSyntax("c#")] string code)
    {
        return SourceText.From(code, Encoding.UTF8);
    }
}